name: uni_fit
description:

publish_to: "none"

version: 1.0.6+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebse (Back-end)
  firebase_auth:
  firebase_core:
  cloud_firestore:
  firebase_database:

  # Google Authentication
  google_sign_in:

  # Font Style
  font_awesome_flutter:

  # # Posture Detecting
  # tflite: ^1.1.2

  # # Camera (live-monitoring)
  # camera: ^0.9.4+14

  # Page transition animation
  page_transition:

  # Celebration animation (end-exercise)
  confetti:

  # Auto slider Container (Home-Page)
  carousel_slider:

  # Running Track
  location: ^4.4.0
  google_maps_flutter: 
  flutter_polyline_points: ^0.2.6
  dio: ^4.0.0

  # Video (Exercise-Diet)
  url_launcher:

  # svg images
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Splash Screen
  flutter_native_splash: ^2.0.1+1
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen_logo.png
  branding: assets/images/branding.png
  branding_mode: bottom
  android: true
  ios: true
  fullscreen: true

  # Icon Luncher
  flutter_launcher_icons:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Images
  assets:
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/svg/
    - assets/svg/uni_logo.svg
    - assets/images/logo.png
    - assets/images/
    - assets/images/diet/
    - assets/images/advance/
    - assets/images/beginner/
    - assets/images/intermediate/
    - assets/images/gif/

  fonts:
      # Bold Font
    - family: popBold
      fonts:
        - asset: assets/font/poppins_bold.otf

      # Light Font
    - family: popLight
      fonts:
        - asset: assets/font/poppins_light.otf

      # Medium Font
    - family: popMedium
      fonts:
        - asset: assets/font/poppins_medium.otf
